name: Code Analysis
on:
  push:
    paths:
      - ".github/codeql.yml"
      - "src/**.js"
      - "index.js"
  pull_request:
    paths:
      - ".github/codeql.yml"
      - "src/**.js"
      - "index.js"
  schedule:
    - cron: "0 7 * * 3"

permissions: read-all

jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.4.0
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1.0.24
      with:
        config-file: ./.github/codeql.yml
        languages: javascript
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1.0.24
